---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Rebecca Gu rjg2836

#### Introduction 

Paragraph or two introducing your datasets and variables, why they are interesting to you, etc.

The datasets I have chosen are college_grad_students and college_all_ages from fivethirtyeight. The data was obtained from American Community Survey 2010-2012 Public Use Microdata Series. college_grad_students, or grad, is a data frame with 173 rows representing majors (graduate vs nongraduate students) and 22 variables. college_all_ages, or all, is a data frame with 173 rows representing majors (all ages) and 11 variables. The variables describe the employment rates, total counts, incomes, major category, and major. "grad" differs from "all" by splitting the first three variables listed before into those who graduated and those who did not. Thus, it contains more specific information than "all". This dataset is interesting to me because choosing college majors seems like a daunting task that controls the rest of your life, and many people pick randomly. I would like to see the quantitative data that shows what majors are the most lucrative. Also, as an Economics major, I feel looked down on since it's Liberal Arts, and it would interest me to see just how much more engineering majors make. I expect engineering to make the most, and for those with degrees to earn significantly more than those who did not. 
```{R}
# read your datasets in here, e.g., with read_csv()
library(tidyverse)
library(knitr)
options(scipen=10000)
library(fivethirtyeight)

grad <- college_grad_students
all <- college_all_ages
```

#### Tidying: Reshaping

If your datasets are tidy already, demonstrate that you can reshape data with pivot wider/longer here (e.g., untidy and then retidy). Alternatively, it may be easier to wait until the wrangling section so you can reshape your summary statistics. Note here if you are going to do this.

```{R}
# Tidyed joined data
```

    
#### Joining/Merging

```{R}
joined <- left_join(all,grad, by="major_code", suffix=c("",".y"))
# total observations/rows in each dataset
dim(all)
dim(grad)
dim(joined)
#unique IDs in each dataset
all %>% count(n_distinct(major_code))
grad %>% count(n_distinct(major_code))
joined %>% count(n_distinct(major_code))
#IDs that appear in one dataset but not the other (and which those are)
anti_join(all, grad, by="major_code")
#IDs the datasets have common
inner_join(all, grad, by="major_code")

joined %>% pivot_wider(names_from = "major_category", values_from  = "total") %>% pivot_longer(29:44, names_to="major_category", values_to="total",values_drop_na=T)


```

Discussions of joining here. Feel encouraged to break up into more than once code chunk and discuss each in turn.


In the original "all" dataset, there were 173 observations and 11 variables, each observation being an unique major. In the "grad" dataset there were 173 observations and 22 variables, each observation being an unique major. I chose left join because I wanted all the information from both datsets, and this allowed me to do that. I could have done inner join but I am not as comfortable with that. I left joined the "grad" dataset to the "all" dataset. They had a common ID of major code, which is a four digit unique identifier for each major. I could have also joined by the major name. Once joined, there were 173 observations and 32 variables, each observation being an unique major. This makes the size of the joined dataset the size of (the two original datasets - 1) because the joined ID variable only counts once. 2/32 variables will be dropped in wrangling. There were no IDs that appeared in one but not the other, and no observations were dropped. I included the suffix parameter because both datasets have "major" and "major_category" as variables. Since I only need one set of them, I uniquely identified the second set with ".y" so that I can easily drop it later with contains().

To demonstrate the use of pivot_longer and pivot_wider, I untidyed the data by untidying the "major_category" column and the "total" column. I then chose all the columns from 29-44 that had the new major categories and pivoted it longer. I had to remove the NAs because for each major there would be 1 real observation and 15 dummy ones that had NA for the total column of the major category it is NOT in. 

####  Wrangling

```{R}

joined %>% select(!contains(".y")) -> joined 
joined %>% arrange(desc(median))%>% group_by(major_category) %>% slice(1:4) 
joined %>% mutate(diffp75=grad_p75th-p75th, diffmed = grad_median-median, diffp25=grad_p25th-p25th)%>% arrange(desc(diffmed)) 
joined %>% filter(total>mean(total)) %>% summarize(mean(median))
joined %>% filter(str_detect(major, "Economics")) 

#summary statistics
joined %>% group_by(major_category) %>% summarize(Count=n())
joined %>% group_by(major_category) %>% summarize(Mean= mean(unemployment_rate),StDev= sd(unemployment_rate),Count = n()) %>%kable(digits = 3, align = 'c',col.names = c("Major Category", "Mean", "StDev", "Count"), caption = "Unemployment Rates")
joined %>% summarize_all(function(x)sum(is.na(x)))
joined %>% group_by(major_category) %>% summarize(AvgDiffQ1= mean(grad_p25th-p25th), AvgDiffMedian= mean(grad_median-median),AvgDiffQ3=mean(grad_p75th-p75th))
joined %>% summarize(min(nongrad_unemployment_rate), min(grad_unemployment_rate), min(nongrad_median), min(grad_median),max(nongrad_unemployment_rate), max(grad_unemployment_rate), max(nongrad_median), max(grad_median))



```

Your discussion of wrangling section here. Feel encouraged to break up into more than once code chunk and discuss each in turn.

The first line of code drops the duplicate columns from the join by selecting the column names that end with ".y". This becomes the new joined set. The second groups by the category then takes the top 4 median incomes of each category. This is because some categories, like business and art, have multiple majors attached to them that are similar. 
The third line of code finds the differences between income by graduates and the entire industry. After arranging, it shows that Health And Medical Preparatory Programs majors earned 85,000 more than the median worker of the industry. Almost all majors, but 2, the median graduate earned more than the median worker. Petroleum engineers make 1000 less and architectural engineering made the same. What if some majors have very few workers but have a high income? I filter to majors that have greater workers than the average of the overall total. This filters to 40 majors that have median incomes of 55702.5. The last line of code allows me to see the different type of economics. I only thought there was 1!

For summary statistics, the counts for the major category was created, and there are 29 engineering majors, making it the most diverse. The unemployment rates for each major category was lower than the US national average of 8.9% in 2012, found from the Bureau of Labor Statistics. To count the number of missing values, I created a function, and it revealed that there were no missing values. The average difference between graduates and the industry for the 3 quartiles were calculated, showing that graduates earned more than the average worker in Q1 and Q2, but not Q3. This was the most interesting finding in the summary statistics. The last line of code compared the min and max of unemployment rate, median income between graduates and nongraduates. Everything favored graduates as they has the highest max and min median income and the lowest unemployment rates. This shows that getting a degree pays off and is of value. 

#### Visualizing

```{R}
set <- joined %>% arrange(desc(median)) %>% head(25)

             
ggplot(set, aes(major,median))+ geom_point(aes(color=major_category, size= median))+ theme(legend.position="right") +scale_size(guide = 'none') + coord_flip()+theme(axis.text.x = element_text(angle = 90))+scale_y_continuous(labels=scales::dollar)+labs(color = "Major Category") +xlab("Major") +ylab("Median Income")+ggtitle("Top 25 Median Incomes Grouped by Category")
```

This plot depicts the top 25 median incomes and their respective majors. They are grouped by the major category, and it is evident that out of the 20 majors, engineering dominates the most. Petroleum Engineering has a median income of $125,000 making it the highest paid. The bigger the circles, the higher the pay. It is interesting to note that Pharmacy Pharmaceutical Sciences And Administration has the second highest income.

```{R}

joined %>% filter(major_category == "Engineering") %>% ggplot()+ geom_line(aes(x=unemployment_rate, y=grad_median,color="Graduates")) + geom_line(aes(x=nongrad_unemployment_rate,y=nongrad_median, color = "Non-Graduates")) +xlab("Unemployment Rate")+ scale_x_continuous(breaks=seq(0, .1, .025),labels=c("0%","2.5%","5%","7.5%", "10%"))+scale_y_continuous(labels=scales::dollar)+ ylab("Median Income")+theme(legend.position = "right") + labs(color= " ")+ggtitle("Unemployment Rates of Graduates vs. Non Graduates in Engineering")
```

This plot compares the unemployment rates and median incomes of graduates vs. non graduates in Engineering. I compare those who had a college degree and those who did not to get a sense of how education is important for engineering jobs. Overall, graduates have around the same unemployment rates, but their median income is much higher almost all of the time than non-graduates. It can be inferred that jobs do not care if you have a degree, but they will pay less.
```{R}
joined %>% ggplot(aes(major_category)) + geom_bar(aes(y=total, fill=major_category),stat="summary", fun=sum)+theme(axis.text.x = element_text(angle=45, hjust=1), 
        legend.position="none") +scale_y_continuous(breaks=seq(0,1000000000,2500000),labels = scales::comma) +ggtitle("Total Workforce") + xlab("Major Category") + ylab("People") 
```
```


This plot shows how the total workforce is distributed throughout the 16 major categories. For each major cateogry, it took the sum of the total number of people with the major for all majors. Business has the most due to 3,123,510 people having a degree in Busiess Management and Administration. As we saw in the first plot, engineering has the highest paying jobs. In this plot, they are the fourth largest category. The top three major categories are not STEM related, which can explain why education is pushing for more STEM majors now. 

#### Concluding Remarks

Majors are an important determinant of income and job stability. Those who are unsure of what major to pick when entering college should research not only the income, but also the lifestyle, workload, and training needed. 




